config/routes.rb
Rails.application.routes.draw do
  root :to => "web/boards#show"

  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resources :developers, only: [:new, :create]
  end

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < User
end

app/models/manager.rb
class Manager < User
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true

  validates :name, presence: true
  validates :description, presence: true
  validates :author, presence: true
  validates :description, length: { maximum: 500 }

  state_machine :initial => :new_task do
    event :to_dev do
      transition [:new_task, :in_qa, :in_code_review] => :in_development
    end
    event :to_qa do
      transition :in_development => :in_qa
    end
    event :to_codereview do
      transition :in_qa => :in_codereview
    end
    event :pre_realease do
      transition :in_codereview => :ready_for_realease
    end
    event :realease do
      transition :ready_for_realease => :realeased
    end
    event :to_archive do
      transition [:new_task, :realesed] => :archived
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :my_tasks, class_name: 'Task', foreign_key: :author_id
  has_many :assigned_tasks, class_name: 'Task', foreign_key: :assignee_id

  validates :first_name, :last_name, :email, presence: true
  validates :first_name, :last_name, length: { minimum: 2 }
  validates :email, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/, uniqueness: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  include Concerns::AuthHelper
  before_action :authenticate_user!, :authorize
  helper_method :current_user

  def authorize
    render :file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false if forbidden?
  end

  def forbidden?
    !current_user.is_a?(Admin)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_url
    else
      render :new_admin_user_url
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_url
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :type)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < Api::ApplicationController
  def build_meta_tasks(collection)
    {
      count: collection.count,
      total_count: collection.total_count,
      current_page: collection.current_page,
      total_pages: collection.total_pages,
      per_page: collection.limit_value
    }
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::ApplicationController
  respond_to :json

  def index
    q_params = params[:q] || { s: 'id asc' }

    tasks = Task.all
                .ransack(q_params)
                .result
                .page(params[:page])
                .per(params[:per_page])

    json = {
      items: tasks.map { |t| TaskSerializer.new(t).as_json },
      meta: build_meta_tasks(tasks)
    }

    respond_with json
  end

  def show
    task = Task.find(params[:id])
    respond_with(task)
  end

  def create
    task = current_user.my_tasks.new(task_params)

    if task.save
      respond_with(task, location: nil)
    else
      render(json: { errors: task.errors }, status: :unprocessable_entity)
    end
  end

  def update
    task = Task.find(params[:id])

    if task.update(task_params)
      render(json: task)
    else
      render(json: { errors: task.errors }, status: unprocessable_entity)
    end
  end

  def destroy
    task = Task.find(params[:id])
    if task.destroy
      head(:ok)
    else
      render(json: { errors: task.errors }, status: unprocessable_entity)
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :author_id, :assignee_id,
                                 :state_event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/auth_helper.rb
module Concerns
  module AuthHelper
    def sign_in(user)
      session[:user_id] = user.id
    end

    def sign_out
      session[:user_id] = nil
    end

    def signed_in?
      current_user.present?
    end

    def authenticate_user!
      redirect_to new_session_path unless signed_in?
    end

    def current_user
      return if session[:user_id].blank?
      @_current_user ||= User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include Concerns::AuthHelper
  helper_method :current_user
end

app/controllers/web/boards_controller.rb
class Web::BoardsController < Web::ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/web/developers_controller.rb
class Web::DevelopersController < Web::ApplicationController
  def new
    @developer = Developer.new
  end


  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      sign_in @developer
      redirect_to :board
    else
      render :new
    end
  end

  private

  def developer_params
    params.require(:developer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)

    if @session.valid?
      sign_in @session.user
      redirect_to :board
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to :new_session
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.slim
  .row
    .col-lg-1
      = f.button :submit, 'Back', formaction: admin_users_url, formmethod: 'get'
    .col-lg-11
      h4  Create new user
  p
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :type, as: :select, collection: ['Admin', 'Manager', 'Developer']

app/views/admin/users/edit.html.slim
= simple_form_for [:admin, @user], as: :user, url: admin_user_url do |f|
  = render 'form', f: f
  = f.button :submit, 'Confirm'

app/views/admin/users/index.html.slim
h3 Users list
= link_to "Add new user", new_admin_user_path
.container
  .row
    .col-lg-10
    .col-lg-2
      = search_form_for(@q, url: admin_users_url, method: :get) do |f|
        = f.search_field :email_cont, placeholder: "Search by email"
table.table
  thead
    tr
      th= sort_link(@q, :id, "#")
      th= sort_link(@q, :first_name, "First Name")
      th= sort_link(@q, :last_name, "Last Name")
      th= sort_link(@q, :email, "Email")
      th= sort_link(@q, :type, "Type")
      th scope="col"  Actions
  tbody
    - @users.each do |user|
      tr
        td= user.id
        td= user.first_name
        td= user.last_name
        td= user.email
        td= user.type
        td
          => link_to "Edit", edit_admin_user_path(user)
          -if current_user.id != user.id
            => link_to "Delete", admin_user_path(user), method: "delete"
= paginate @users
= page_entries_info @users

app/views/admin/users/new.html.slim
= simple_form_for @user, url: new_admin_user_path do |f|
  = render 'form', f: f
  = f.button :submit, 'Create', formaction: admin_users_path

app/views/admin/users/show.html.slim
h1 User profile
p
  span First Name:&nbsp;
  strong= @user.first_name
p
  span Last Name:&nbsp;
  strong= @user.last_name
p
  span Email:&nbsp;
  strong= @user.email

= link_to "Back to index", admin_users_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Task Manager"
    = javascript_include_tag "application"
    = javascript_pack_tag "application"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        .row
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          .col-lg-9
            a.navbar-brand href=root_path Task Manager
            - if current_user
              .navbar-collapse.collapse.navbar-responsive-collapse
                ul.nav.navbar-nav
                  li= link_to "Board", root_path
                  - if current_user.is_a? Admin
                    li= link_to "Admin page", admin_users_url
          .col-lg-3
            ul.nav.navbar-nav
              -if current_user
                li= link_to current_user.name
                li= link_to "Log out", session_path, method: "delete"
              -else
                li= link_to "Sign in", new_session_path
                li= link_to "Sign up", new_developer_path

  .container
    .row
      .col-lg-12
        = bootstrap_flash
        = yield

    footer
      p
      p &copy; Company 2018

app/views/web/boards/show.html.slim
h1 Web::Boards#show
p Find me in app/views/web/boards/show.html.slim
= react_component('TaskBoard')

app/views/web/developers/new.html.slim
.container
  .new
    .col-lg-3
      h3 Sign in

      = simple_form_for @developer do |f|
        = f.input :first_name
        = f.input :last_name
        = f.input :email
        = f.input :password
        = f.input :password_confirmation
        = f.button :submit, "Sign up"